import { NextResponse } from 'next/server';

export async function GET() {
  const now = new Date();
  const ts = (minsAgo: number) => new Date(now.getTime() - minsAgo * 60000).toISOString();

  // ─── Vendor Platforms (Aggregators) ──────────────────────────────────────────
  const platforms = [
    {
      id: 'plat-001',
      name: 'EveryMatrix',
      slug: 'everymatrix',
      type: 'aggregator',
      status: 'active',
      description: 'Leading B2B iGaming platform offering casino, sports, and payment integration through a single API.',
      website: 'https://www.everymatrix.com',
      integrationType: 'rest_api',
      apiVersion: 'v2.4',
      baseUrl: 'https://api.everymatrix.com/v2',
      callbackUrl: 'https://tols-casino.com/callbacks/everymatrix',
      apiKey: 'ak_em_***...f7a2',
      secretKey: 'sk_em_***...d91c',
      ipWhitelist: ['34.240.12.0/24', '34.240.13.0/24', '52.214.0.0/16'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'BRL', 'SEK', 'NOK'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ja', 'ko', 'zh', 'sv', 'no', 'fi'],
      totalProviders: 12,
      totalGames: 4200,
      activeGames: 3850,
      isActive: true,
      health: { uptime: 99.98, errorRate: 0.12, avgLatencyMs: 38, lastCheck: ts(3) },
      joinedAt: '2021-06-15T00:00:00.000Z',
    },
    {
      id: 'plat-002',
      name: 'SoftSwiss',
      slug: 'softswiss',
      type: 'aggregator',
      status: 'active',
      description: 'Turnkey casino solution and game aggregation platform supporting 10,000+ games from 80+ providers.',
      website: 'https://www.softswiss.com',
      integrationType: 'rest_api',
      apiVersion: 'v3.1',
      baseUrl: 'https://api.softswiss.com/v3',
      callbackUrl: 'https://tols-casino.com/callbacks/softswiss',
      apiKey: 'ak_ss_***...b3e8',
      secretKey: 'sk_ss_***...a72f',
      ipWhitelist: ['45.136.12.0/24', '45.136.13.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'BTC', 'ETH', 'USDT', 'LTC', 'BCH', 'DOGE'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ru', 'ja', 'zh', 'uk'],
      totalProviders: 18,
      totalGames: 10500,
      activeGames: 9800,
      isActive: true,
      health: { uptime: 99.95, errorRate: 0.18, avgLatencyMs: 52, lastCheck: ts(5) },
      joinedAt: '2021-09-20T00:00:00.000Z',
    },
    {
      id: 'plat-003',
      name: 'Slotegrator',
      slug: 'slotegrator',
      type: 'aggregator',
      status: 'active',
      description: 'Casino game aggregator and bonus engine providing seamless integration of 3,000+ games.',
      website: 'https://www.slotegrator.com',
      integrationType: 'soap_rest',
      apiVersion: 'v1.8',
      baseUrl: 'https://api.slotegrator.com/v1',
      callbackUrl: 'https://tols-casino.com/callbacks/slotegrator',
      apiKey: 'ak_sl_***...c5d9',
      secretKey: 'sk_sl_***...e12a',
      ipWhitelist: ['91.223.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'RUB', 'KZT', 'UAH', 'GEL'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ru', 'uk', 'ka'],
      totalProviders: 10,
      totalGames: 3100,
      activeGames: 2750,
      isActive: true,
      health: { uptime: 99.91, errorRate: 0.25, avgLatencyMs: 65, lastCheck: ts(8) },
      joinedAt: '2022-01-10T00:00:00.000Z',
    },
    {
      id: 'plat-004',
      name: 'NuxGame',
      slug: 'nuxgame',
      type: 'aggregator',
      status: 'suspended',
      description: 'Multi-provider casino integration platform with focus on crypto-friendly gaming solutions.',
      website: 'https://www.nuxgame.com',
      integrationType: 'rest_api',
      apiVersion: 'v2.0',
      baseUrl: 'https://api.nuxgame.com/v2',
      callbackUrl: 'https://tols-casino.com/callbacks/nuxgame',
      apiKey: 'ak_ng_***...f8b1',
      secretKey: 'sk_ng_***...c4e7',
      ipWhitelist: ['195.201.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'BTC', 'ETH', 'USDT', 'LTC'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ru'],
      totalProviders: 8,
      totalGames: 2200,
      activeGames: 1800,
      isActive: false,
      health: { uptime: 98.72, errorRate: 1.35, avgLatencyMs: 120, lastCheck: ts(45) },
      joinedAt: '2022-05-01T00:00:00.000Z',
    },
    {
      id: 'plat-005',
      name: 'BetConstruct',
      slug: 'betconstruct',
      type: 'aggregator',
      status: 'active',
      description: 'Comprehensive iGaming platform offering sports betting, casino, live dealer, and virtual games.',
      website: 'https://www.betconstruct.com',
      integrationType: 'soap_rest',
      apiVersion: 'v4.0',
      baseUrl: 'https://api.betconstruct.com/v4',
      callbackUrl: 'https://tols-casino.com/callbacks/betconstruct',
      apiKey: 'ak_bc_***...a3d5',
      secretKey: 'sk_bc_***...b9f2',
      ipWhitelist: ['5.188.12.0/24', '5.188.13.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'RUB', 'AMD', 'GEL', 'KZT'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ru', 'hy', 'ka', 'uk'],
      totalProviders: 14,
      totalGames: 5600,
      activeGames: 5100,
      isActive: true,
      health: { uptime: 99.88, errorRate: 0.22, avgLatencyMs: 48, lastCheck: ts(2) },
      joinedAt: '2022-08-15T00:00:00.000Z',
    },
  ];

  // ─── Game Providers ────────────────────────────────────────────────────────
  const providers = [
    {
      id: 'prov-001',
      name: 'Evolution Gaming',
      slug: 'evolution-gaming',
      type: 'live_casino',
      status: 'active',
      vendorId: 'plat-001',
      website: 'https://www.evolution.com',
      integrationType: 'api',
      apiVersion: 'v3.2',
      baseUrl: 'https://api.evolution.com',
      callbackUrl: 'https://tols-casino.com/callbacks/evolution',
      allowedIps: ['185.26.156.0/24', '185.26.157.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'BRL'],
      totalGames: 340,
      activeGames: 328,
      activePlayers: 12450,
      monthlyRevenue: 4200000,
      errorRate: 0.3,
      avgLatencyMs: 45,
      uptime: 99.97,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-002',
      name: 'Pragmatic Play',
      slug: 'pragmatic-play',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-001',
      website: 'https://www.pragmaticplay.com',
      integrationType: 'api',
      apiVersion: 'v2.8',
      baseUrl: 'https://api.pragmaticplay.com',
      callbackUrl: 'https://tols-casino.com/callbacks/pragmatic',
      allowedIps: ['178.33.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL', 'INR', 'IDR', 'VND'],
      totalGames: 520,
      activeGames: 495,
      activePlayers: 18920,
      monthlyRevenue: 3100000,
      errorRate: 0.15,
      avgLatencyMs: 32,
      uptime: 99.99,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-003',
      name: 'NetEnt',
      slug: 'netent',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-002',
      website: 'https://www.netent.com',
      integrationType: 'api',
      apiVersion: 'v2.1',
      baseUrl: 'https://api.netent.com',
      callbackUrl: 'https://tols-casino.com/callbacks/netent',
      allowedIps: ['193.104.12.0/24', '193.105.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK', 'NOK', 'CAD'],
      totalGames: 280,
      activeGames: 265,
      activePlayers: 9560,
      monthlyRevenue: 2800000,
      errorRate: 0.08,
      avgLatencyMs: 28,
      uptime: 99.99,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-004',
      name: 'Microgaming',
      slug: 'microgaming',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-002',
      website: 'https://www.microgaming.com',
      integrationType: 'soap',
      apiVersion: 'v1.5',
      baseUrl: 'https://api.microgaming.com',
      callbackUrl: 'https://tols-casino.com/callbacks/microgaming',
      allowedIps: ['94.236.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'ZAR', 'NZD', 'CAD'],
      totalGames: 850,
      activeGames: 780,
      activePlayers: 15200,
      monthlyRevenue: 2600000,
      errorRate: 0.45,
      avgLatencyMs: 55,
      uptime: 99.92,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-005',
      name: "Play'n GO",
      slug: 'playngo',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-003',
      website: 'https://www.playngo.com',
      integrationType: 'api',
      apiVersion: 'v2.5',
      baseUrl: 'https://api.playngo.com',
      callbackUrl: 'https://tols-casino.com/callbacks/playngo',
      allowedIps: ['31.3.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK', 'NOK', 'JPY'],
      totalGames: 310,
      activeGames: 298,
      activePlayers: 11300,
      monthlyRevenue: 2200000,
      errorRate: 0.12,
      avgLatencyMs: 35,
      uptime: 99.96,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-006',
      name: 'Yggdrasil',
      slug: 'yggdrasil',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-001',
      website: 'https://www.yggdrasilgaming.com',
      integrationType: 'api',
      apiVersion: 'v1.9',
      baseUrl: 'https://api.yggdrasilgaming.com',
      callbackUrl: 'https://tols-casino.com/callbacks/yggdrasil',
      allowedIps: ['46.21.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'NOK', 'SEK', 'DKK'],
      totalGames: 145,
      activeGames: 138,
      activePlayers: 6700,
      monthlyRevenue: 1500000,
      errorRate: 0.18,
      avgLatencyMs: 42,
      uptime: 99.94,
      isCertified: true,
      isActive: true,
    },
    {
      id: 'prov-007',
      name: 'Quickspin',
      slug: 'quickspin',
      type: 'slots',
      status: 'pending',
      vendorId: 'plat-003',
      website: 'https://www.quickspin.com',
      integrationType: 'api',
      apiVersion: 'v1.4',
      baseUrl: 'https://api.quickspin.com',
      callbackUrl: 'https://tols-casino.com/callbacks/quickspin',
      allowedIps: ['91.108.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK', 'NOK'],
      totalGames: 95,
      activeGames: 88,
      activePlayers: 4200,
      monthlyRevenue: 890000,
      errorRate: 0.32,
      avgLatencyMs: 48,
      uptime: 99.85,
      isCertified: false,
      isActive: false,
    },
    {
      id: 'prov-008',
      name: 'Red Tiger',
      slug: 'red-tiger',
      type: 'slots',
      status: 'active',
      vendorId: 'plat-002',
      website: 'https://www.redtigergaming.com',
      integrationType: 'api',
      apiVersion: 'v2.0',
      baseUrl: 'https://api.redtigergaming.com',
      callbackUrl: 'https://tols-casino.com/callbacks/redtiger',
      allowedIps: ['52.56.12.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'CAD'],
      totalGames: 175,
      activeGames: 168,
      activePlayers: 7800,
      monthlyRevenue: 1350000,
      errorRate: 0.09,
      avgLatencyMs: 30,
      uptime: 99.98,
      isCertified: true,
      isActive: true,
    },
  ];

  // ─── Callback Endpoints ─────────────────────────────────────────────────────
  const callbacks = [
    { id: 'cb-001', providerId: 'prov-001', name: 'Game Launch', eventType: 'game.launch', url: '/callbacks/evolution/game-launch', method: 'POST', authType: 'hmac', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.8, totalReceived: 285400, totalSuccess: 284832, totalFailed: 568, lastReceivedAt: ts(2), lastSuccessAt: ts(2) },
    { id: 'cb-002', providerId: 'prov-001', name: 'Game Close', eventType: 'game.close', url: '/callbacks/evolution/game-close', method: 'POST', authType: 'hmac', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.9, totalReceived: 285300, totalSuccess: 285015, totalFailed: 285, lastReceivedAt: ts(3), lastSuccessAt: ts(3) },
    { id: 'cb-003', providerId: 'prov-001', name: 'Bet Placement', eventType: 'bet.place', url: '/callbacks/evolution/bet-place', method: 'POST', authType: 'hmac', isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500 }, timeoutMs: 3000, successRate: 99.95, totalReceived: 1420000, totalSuccess: 1419290, totalFailed: 710, lastReceivedAt: ts(1), lastSuccessAt: ts(1) },
    { id: 'cb-004', providerId: 'prov-002', name: 'Win Register', eventType: 'win.register', url: '/callbacks/pragmatic/win-register', method: 'POST', authType: 'api_key', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.92, totalReceived: 892000, totalSuccess: 891286, totalFailed: 714, lastReceivedAt: ts(1), lastSuccessAt: ts(1) },
    { id: 'cb-005', providerId: 'prov-002', name: 'Session Start', eventType: 'session.start', url: '/callbacks/pragmatic/session-start', method: 'POST', authType: 'api_key', isActive: true, retryPolicy: { maxRetries: 2, backoffMs: 2000 }, timeoutMs: 8000, successRate: 99.7, totalReceived: 189200, totalSuccess: 188632, totalFailed: 568, lastReceivedAt: ts(5), lastSuccessAt: ts(5) },
    { id: 'cb-006', providerId: 'prov-003', name: 'Session End', eventType: 'session.end', url: '/callbacks/netent/session-end', method: 'POST', authType: 'ip_whitelist', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.85, totalReceived: 95600, totalSuccess: 94456, totalFailed: 1144, lastReceivedAt: ts(8), lastSuccessAt: ts(8) },
    { id: 'cb-007', providerId: 'prov-004', name: 'Bonus Trigger', eventType: 'bonus.trigger', url: '/callbacks/microgaming/bonus-trigger', method: 'POST', authType: 'bearer', isActive: true, retryPolicy: { maxRetries: 2, backoffMs: 2000 }, timeoutMs: 10000, successRate: 99.5, totalReceived: 45200, totalSuccess: 44974, totalFailed: 226, lastReceivedAt: ts(15), lastSuccessAt: ts(15) },
    { id: 'cb-008', providerId: 'prov-005', name: 'Error Report', eventType: 'error.report', url: '/callbacks/playngo/error-report', method: 'POST', authType: 'api_key', isActive: true, retryPolicy: { maxRetries: 1, backoffMs: 5000 }, timeoutMs: 15000, successRate: 98.2, totalReceived: 3200, totalSuccess: 3142, totalFailed: 58, lastReceivedAt: ts(30), lastSuccessAt: ts(30) },
    { id: 'cb-009', providerId: 'prov-001', name: 'Balance Check', eventType: 'balance.check', url: '/callbacks/evolution/balance-check', method: 'GET', authType: 'hmac', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 500 }, timeoutMs: 3000, successRate: 99.98, totalReceived: 568000, totalSuccess: 567886, totalFailed: 114, lastReceivedAt: ts(0.5), lastSuccessAt: ts(0.5) },
    { id: 'cb-010', providerId: 'prov-002', name: 'Player Validate', eventType: 'player.validate', url: '/callbacks/pragmatic/player-validate', method: 'POST', authType: 'api_key', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.9, totalReceived: 189200, totalSuccess: 189011, totalFailed: 189, lastReceivedAt: ts(4), lastSuccessAt: ts(4) },
    { id: 'cb-011', providerId: 'prov-006', name: 'Game Launch', eventType: 'game.launch', url: '/callbacks/yggdrasil/game-launch', method: 'POST', authType: 'bearer', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000 }, timeoutMs: 5000, successRate: 99.75, totalReceived: 67000, totalSuccess: 66833, totalFailed: 167, lastReceivedAt: ts(6), lastSuccessAt: ts(6) },
    { id: 'cb-012', providerId: 'prov-008', name: 'Win Register', eventType: 'win.register', url: '/callbacks/redtiger/win-register', method: 'POST', authType: 'api_key', isActive: false, retryPolicy: { maxRetries: 2, backoffMs: 1500 }, timeoutMs: 5000, successRate: 0, totalReceived: 0, totalSuccess: 0, totalFailed: 0, lastReceivedAt: null, lastSuccessAt: null },
    { id: 'cb-013', providerId: 'prov-007', name: 'Session Start', eventType: 'session.start', url: '/callbacks/quickspin/session-start', method: 'POST', authType: 'ip_whitelist', isActive: false, retryPolicy: { maxRetries: 2, backoffMs: 2000 }, timeoutMs: 8000, successRate: 0, totalReceived: 0, totalSuccess: 0, totalFailed: 0, lastReceivedAt: null, lastSuccessAt: null },
    { id: 'cb-014', providerId: 'prov-004', name: 'Balance Check', eventType: 'balance.check', url: '/callbacks/microgaming/balance-check', method: 'GET', authType: 'bearer', isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 500 }, timeoutMs: 3000, successRate: 99.88, totalReceived: 304000, totalSuccess: 303635, totalFailed: 365, lastReceivedAt: ts(1), lastSuccessAt: ts(1) },
  ];

  // ─── Credentials ────────────────────────────────────────────────────────────
  const credentials = [
    { id: 'cred-001', providerId: 'prov-001', environment: 'production', apiKey: 'ak_evo_prod_a7f2...d91c', apiSecret: 'sk_evo_prod_8b3e...f4a2', bearerToken: 'eyJhbGciOi...truncated', isActive: true, lastUsedAt: ts(1), expiresAt: '2026-06-15T00:00:00.000Z' },
    { id: 'cred-002', providerId: 'prov-001', environment: 'staging', apiKey: 'ak_evo_stg_c1d8...e5b3', apiSecret: 'sk_evo_stg_4f6a...c72d', bearerToken: null, isActive: true, lastUsedAt: ts(60), expiresAt: '2026-03-20T00:00:00.000Z' },
    { id: 'cred-003', providerId: 'prov-001', environment: 'sandbox', apiKey: 'ak_evo_sbx_f9a1...b6c4', apiSecret: 'sk_evo_sbx_2d8f...a31e', bearerToken: null, isActive: true, lastUsedAt: ts(1440), expiresAt: '2026-12-01T00:00:00.000Z' },
    { id: 'cred-004', providerId: 'prov-002', environment: 'production', apiKey: 'ak_pp_prod_e3c7...a82f', apiSecret: 'sk_pp_prod_1b5d...f96c', bearerToken: 'eyJhbGciOi...truncated', isActive: true, lastUsedAt: ts(2), expiresAt: '2026-09-01T00:00:00.000Z' },
    { id: 'cred-005', providerId: 'prov-002', environment: 'staging', apiKey: 'ak_pp_stg_d6f2...c91a', apiSecret: 'sk_pp_stg_7a4e...b53f', bearerToken: null, isActive: true, lastUsedAt: ts(120), expiresAt: '2026-04-15T00:00:00.000Z' },
    { id: 'cred-006', providerId: 'prov-003', environment: 'production', apiKey: 'ak_ne_prod_b8d4...e17c', apiSecret: 'sk_ne_prod_3c9f...d68a', bearerToken: null, isActive: true, lastUsedAt: ts(5), expiresAt: '2025-07-10T00:00:00.000Z' },
    { id: 'cred-007', providerId: 'prov-004', environment: 'production', apiKey: 'ak_mg_prod_a1e5...f23b', apiSecret: 'sk_mg_prod_6d2c...c84e', bearerToken: 'eyJhbGciOi...truncated', isActive: true, lastUsedAt: ts(3), expiresAt: '2026-01-20T00:00:00.000Z' },
    { id: 'cred-008', providerId: 'prov-005', environment: 'production', apiKey: 'ak_pn_prod_c4f8...d35a', apiSecret: 'sk_pn_prod_9e1b...a72f', bearerToken: null, isActive: true, lastUsedAt: ts(8), expiresAt: '2025-04-05T00:00:00.000Z' },
    { id: 'cred-009', providerId: 'prov-006', environment: 'production', apiKey: 'ak_yg_prod_f2a7...b19d', apiSecret: 'sk_yg_prod_5b8e...e46c', bearerToken: null, isActive: true, lastUsedAt: ts(12), expiresAt: '2026-08-30T00:00:00.000Z' },
    { id: 'cred-010', providerId: 'prov-007', environment: 'staging', apiKey: 'ak_qs_stg_e8c3...a52f', apiSecret: 'sk_qs_stg_2f7d...b91e', bearerToken: null, isActive: false, lastUsedAt: ts(10080), expiresAt: '2025-02-15T00:00:00.000Z' },
    { id: 'cred-011', providerId: 'prov-008', environment: 'production', apiKey: 'ak_rt_prod_d1b6...c78e', apiSecret: 'sk_rt_prod_4a9f...f31d', bearerToken: 'eyJhbGciOi...truncated', isActive: true, lastUsedAt: ts(4), expiresAt: '2026-11-10T00:00:00.000Z' },
    { id: 'cred-012', providerId: 'prov-008', environment: 'sandbox', apiKey: 'ak_rt_sbx_b5e9...d42f', apiSecret: 'sk_rt_sbx_8c2a...a65b', bearerToken: null, isActive: true, lastUsedAt: ts(4320), expiresAt: '2027-01-01T00:00:00.000Z' },
  ];

  // ─── Game Catalog ───────────────────────────────────────────────────────────
  const games = [
    { id: 'game-001', providerId: 'prov-001', externalId: 'evo_bac_auto', name: 'Auto Baccarat', slug: 'auto-baccarat', type: 'live_table', category: 'Baccarat', rtp: 98.94, volatility: 'low', maxWin: 50000, maxBet: 10000, minBet: 1, isActive: true, isFeatured: true, isNew: false, totalSessions: 284500, popularityScore: 96 },
    { id: 'game-002', providerId: 'prov-001', externalId: 'evo_blt_mont', name: 'Lightning Roulette', slug: 'lightning-roulette', type: 'live_table', category: 'Roulette', rtp: 97.3, volatility: 'high', maxWin: 500000, maxBet: 5000, minBet: 0.1, isActive: true, isFeatured: true, isNew: false, totalSessions: 412000, popularityScore: 99 },
    { id: 'game-003', providerId: 'prov-001', externalId: 'evo_crazy_time', name: 'Crazy Time', slug: 'crazy-time', type: 'live_table', category: 'Game Show', rtp: 96.17, volatility: 'very_high', maxWin: 2000000, maxBet: 5000, minBet: 0.1, isActive: true, isFeatured: true, isNew: false, totalSessions: 356000, popularityScore: 98 },
    { id: 'game-004', providerId: 'prov-002', externalId: 'pp_dog_house', name: 'The Dog House', slug: 'the-dog-house', type: 'slot', category: 'Video Slot', rtp: 96.51, volatility: 'high', maxWin: 18750, maxBet: 100, minBet: 0.2, isActive: true, isFeatured: false, isNew: false, totalSessions: 198000, popularityScore: 85 },
    { id: 'game-005', providerId: 'prov-002', externalId: 'pp_gates_olymp', name: 'Gates of Olympus', slug: 'gates-of-olympus', type: 'slot', category: 'Video Slot', rtp: 96.5, volatility: 'high', maxWin: 5000, maxBet: 100, minBet: 0.2, isActive: true, isFeatured: true, isNew: false, totalSessions: 524000, popularityScore: 97 },
    { id: 'game-006', providerId: 'prov-002', externalId: 'pp_sugar_rush', name: 'Sugar Rush', slug: 'sugar-rush', type: 'slot', category: 'Video Slot', rtp: 96.5, volatility: 'high', maxWin: 5000, maxBet: 100, minBet: 0.2, isActive: true, isFeatured: false, isNew: true, totalSessions: 89000, popularityScore: 78 },
    { id: 'game-007', providerId: 'prov-003', externalId: 'ne_starburst', name: 'Starburst', slug: 'starburst', type: 'slot', category: 'Video Slot', rtp: 96.09, volatility: 'low', maxWin: 500, maxBet: 100, minBet: 0.1, isActive: true, isFeatured: true, isNew: false, totalSessions: 678000, popularityScore: 92 },
    { id: 'game-008', providerId: 'prov-003', externalId: 'ne_gonzo', name: 'Gonzo\'s Quest', slug: 'gonzos-quest', type: 'slot', category: 'Video Slot', rtp: 95.97, volatility: 'medium', maxWin: 2500, maxBet: 50, minBet: 0.2, isActive: true, isFeatured: false, isNew: false, totalSessions: 345000, popularityScore: 88 },
    { id: 'game-009', providerId: 'prov-004', externalId: 'mg_mega_moolah', name: 'Mega Moolah', slug: 'mega-moolah', type: 'jackpot', category: 'Progressive Jackpot', rtp: 88.12, volatility: 'very_high', maxWin: 18000000, maxBet: 6.25, minBet: 0.01, isActive: true, isFeatured: true, isNew: false, totalSessions: 234000, popularityScore: 94 },
    { id: 'game-010', providerId: 'prov-004', externalId: 'mg_immortal', name: 'Immortal Romance', slug: 'immortal-romance', type: 'slot', category: 'Video Slot', rtp: 96.01, volatility: 'high', maxWin: 3600, maxBet: 30, minBet: 0.3, isActive: true, isFeatured: false, isNew: false, totalSessions: 156000, popularityScore: 79 },
    { id: 'game-011', providerId: 'prov-005', externalId: 'pn_book_dead', name: 'Book of Dead', slug: 'book-of-dead', type: 'slot', category: 'Video Slot', rtp: 96.21, volatility: 'high', maxWin: 5000, maxBet: 100, minBet: 0.1, isActive: true, isFeatured: true, isNew: false, totalSessions: 567000, popularityScore: 95 },
    { id: 'game-012', providerId: 'prov-005', externalId: 'pn_reactoonz', name: 'Reactoonz', slug: 'reactoonz', type: 'slot', category: 'Video Slot', rtp: 96.51, volatility: 'high', maxWin: 4570, maxBet: 100, minBet: 0.2, isActive: true, isFeatured: false, isNew: false, totalSessions: 213000, popularityScore: 82 },
    { id: 'game-013', providerId: 'prov-006', externalId: 'yg_vikings', name: 'Vikings Go Berzerk', slug: 'vikings-go-berzerk', type: 'slot', category: 'Video Slot', rtp: 96.1, volatility: 'high', maxWin: 4000, maxBet: 50, minBet: 0.1, isActive: true, isFeatured: false, isNew: false, totalSessions: 124000, popularityScore: 74 },
    { id: 'game-014', providerId: 'prov-008', externalId: 'rt_gonzo_meg', name: 'Gonzo\'s Quest Megaways', slug: 'gonzos-quest-megaways', type: 'slot', category: 'Video Slot', rtp: 95.77, volatility: 'high', maxWin: 2100, maxBet: 10, minBet: 0.1, isActive: true, isFeatured: true, isNew: true, totalSessions: 78000, popularityScore: 81 },
    { id: 'game-015', providerId: 'prov-008', externalId: 'rt_dragon_fire', name: 'Dragon\'s Fire Megaways', slug: 'dragons-fire-megaways', type: 'slot', category: 'Video Slot', rtp: 95.77, volatility: 'high', maxWin: 10384, maxBet: 10, minBet: 0.1, isActive: true, isFeatured: false, isNew: true, totalSessions: 45000, popularityScore: 68 },
    { id: 'game-016', providerId: 'prov-007', externalId: 'qs_big_bad_wolf', name: 'Big Bad Wolf', slug: 'big-bad-wolf', type: 'slot', category: 'Video Slot', rtp: 97.33, volatility: 'medium', maxWin: 1268, maxBet: 100, minBet: 0.25, isActive: false, isFeatured: false, isNew: false, totalSessions: 34000, popularityScore: 55 },
    { id: 'game-017', providerId: 'prov-002', externalId: 'pp_wild_west', name: 'Wild West Gold', slug: 'wild-west-gold', type: 'slot', category: 'Video Slot', rtp: 96.51, volatility: 'high', maxWin: 18750, maxBet: 100, minBet: 0.2, isActive: true, isFeatured: false, isNew: false, totalSessions: 167000, popularityScore: 76 },
  ];

  // ─── Health Logs ────────────────────────────────────────────────────────────
  const healthLogs = [
    { id: 'hl-001', providerId: 'prov-001', metric: 'uptime', value: 99.97, unit: '%', threshold: 99.5, isAlert: false, details: 'System healthy, all endpoints responsive', checkedAt: ts(3) },
    { id: 'hl-002', providerId: 'prov-001', metric: 'error_rate', value: 0.3, unit: '%', threshold: 1.0, isAlert: false, details: 'Error rate within acceptable bounds', checkedAt: ts(3) },
    { id: 'hl-003', providerId: 'prov-001', metric: 'latency', value: 45, unit: 'ms', threshold: 100, isAlert: false, details: 'Average response time normal', checkedAt: ts(3) },
    { id: 'hl-004', providerId: 'prov-002', metric: 'uptime', value: 99.99, unit: '%', threshold: 99.5, isAlert: false, details: 'Excellent uptime, zero incidents', checkedAt: ts(5) },
    { id: 'hl-005', providerId: 'prov-002', metric: 'error_rate', value: 0.15, unit: '%', threshold: 1.0, isAlert: false, details: 'Below threshold', checkedAt: ts(5) },
    { id: 'hl-006', providerId: 'prov-002', metric: 'latency', value: 32, unit: 'ms', threshold: 100, isAlert: false, details: 'Fast response times', checkedAt: ts(5) },
    { id: 'hl-007', providerId: 'prov-003', metric: 'uptime', value: 99.99, unit: '%', threshold: 99.5, isAlert: false, details: 'Perfect uptime streak', checkedAt: ts(8) },
    { id: 'hl-008', providerId: 'prov-003', metric: 'latency', value: 28, unit: 'ms', threshold: 100, isAlert: false, details: 'Optimal latency', checkedAt: ts(8) },
    { id: 'hl-009', providerId: 'prov-004', metric: 'error_rate', value: 0.45, unit: '%', threshold: 1.0, isAlert: false, details: 'Slightly elevated but within bounds', checkedAt: ts(10) },
    { id: 'hl-010', providerId: 'prov-004', metric: 'latency', value: 55, unit: 'ms', threshold: 100, isAlert: false, details: 'SOAP overhead contributing to higher latency', checkedAt: ts(10) },
    { id: 'hl-011', providerId: 'prov-005', metric: 'uptime', value: 99.96, unit: '%', threshold: 99.5, isAlert: false, details: 'Minor scheduled maintenance window', checkedAt: ts(12) },
    { id: 'hl-012', providerId: 'prov-005', metric: 'latency', value: 35, unit: 'ms', threshold: 100, isAlert: false, details: 'Normal response time', checkedAt: ts(12) },
    { id: 'hl-013', providerId: 'prov-006', metric: 'uptime', value: 99.94, unit: '%', threshold: 99.5, isAlert: false, details: 'Acceptable uptime', checkedAt: ts(15) },
    { id: 'hl-014', providerId: 'prov-006', metric: 'error_rate', value: 0.18, unit: '%', threshold: 1.0, isAlert: false, details: 'Normal error rate', checkedAt: ts(15) },
    { id: 'hl-015', providerId: 'prov-007', metric: 'uptime', value: 99.85, unit: '%', threshold: 99.5, isAlert: true, details: 'Uptime below SLA threshold of 99.9%', checkedAt: ts(20) },
    { id: 'hl-016', providerId: 'prov-007', metric: 'error_rate', value: 0.32, unit: '%', threshold: 1.0, isAlert: false, details: 'Error rate acceptable but monitoring closely', checkedAt: ts(20) },
    { id: 'hl-017', providerId: 'prov-007', metric: 'latency', value: 48, unit: 'ms', threshold: 100, isAlert: false, details: 'Normal latency', checkedAt: ts(20) },
    { id: 'hl-018', providerId: 'prov-008', metric: 'uptime', value: 99.98, unit: '%', threshold: 99.5, isAlert: false, details: 'Excellent uptime', checkedAt: ts(7) },
    { id: 'hl-019', providerId: 'prov-008', metric: 'error_rate', value: 0.09, unit: '%', threshold: 1.0, isAlert: false, details: 'Very low error rate', checkedAt: ts(7) },
    { id: 'hl-020', providerId: 'prov-004', metric: 'api_connectivity', value: 1, unit: 'status', threshold: 1, isAlert: false, details: 'API endpoint connectivity verified', checkedAt: ts(6) },
    { id: 'hl-021', providerId: 'prov-001', metric: 'callback_success', value: 99.8, unit: '%', threshold: 99.0, isAlert: false, details: 'All callbacks performing well', checkedAt: ts(2) },
    { id: 'hl-022', providerId: 'prov-002', metric: 'callback_success', value: 99.92, unit: '%', threshold: 99.0, isAlert: false, details: 'Callback delivery excellent', checkedAt: ts(4) },
    { id: 'hl-023', providerId: 'prov-004', metric: 'uptime', value: 99.92, unit: '%', threshold: 99.5, isAlert: false, details: 'Uptime within SLA but near threshold', checkedAt: ts(10) },
    { id: 'hl-024', providerId: 'prov-001', metric: 'latency', value: 120, unit: 'ms', threshold: 100, isAlert: true, details: 'Latency spike detected during peak hours', checkedAt: ts(1) },
  ];

  // ─── Stats ──────────────────────────────────────────────────────────────────
  const stats = {
    totalPlatforms: platforms.length,
    activePlatforms: platforms.filter(p => p.status === 'active').length,
    totalProviders: providers.length,
    activeProviders: providers.filter(p => p.status === 'active').length,
    totalGames: games.length,
    activeGames: games.filter(g => g.isActive).length,
    totalCallbacks: callbacks.length,
    activeCallbacks: callbacks.filter(c => c.isActive).length,
    totalActivePlayers: providers.reduce((sum, p) => sum + p.activePlayers, 0),
    totalMonthlyRevenue: providers.reduce((sum, p) => sum + p.monthlyRevenue, 0),
    avgUptime: Number((providers.reduce((sum, p) => sum + p.uptime, 0) / providers.length).toFixed(2)),
    avgErrorRate: Number((providers.reduce((sum, p) => sum + p.errorRate, 0) / providers.length).toFixed(2)),
  };

  return NextResponse.json({
    platforms,
    providers,
    callbacks,
    credentials,
    games,
    healthLogs,
    stats,
  });
}
