import { NextResponse } from 'next/server';

export async function GET() {
  const now = new Date();
  const ts = (minsAgo: number) => new Date(now.getTime() - minsAgo * 60000).toISOString();

  // ─── Providers ────────────────────────────────────────────────────────────────
  const providers = [
    {
      id: 'prov-001',
      name: 'Evolution Gaming',
      slug: 'evolution-gaming',
      type: 'live_casino',
      status: 'active',
      logoUrl: '/logos/evolution.svg',
      website: 'https://www.evolution.com',
      description: 'Premium live casino solutions with industry-leading game variety and streaming quality.',
      integrationType: 'api',
      apiVersion: 'v3.2',
      baseUrl: 'https://api.evolution.com',
      callbackUrl: 'https://tols-casino.com/callbacks/evolution',
      secretKey: 'sk_***...evo',
      apiKey: 'ak_***...evo',
      allowedIps: ['185.26.156.0/24', '185.26.157.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'BRL'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'ja', 'ko', 'zh'],
      maxConcurrentSessions: 5000,
      defaultRtp: 97.3,
      isActive: true,
      isCertified: true,
      certifiedAt: '2023-01-15T00:00:00.000Z',
      lastHealthCheck: ts(2),
      totalGames: 340,
      activeGames: 328,
      activePlayers: 12450,
      monthlyRevenue: 4200000,
      errorRate: 0.3,
      avgLatencyMs: 45,
      uptime: 99.97,
      joinedAt: '2022-03-10T00:00:00.000Z',
      createdAt: '2022-03-10T00:00:00.000Z',
    },
    {
      id: 'prov-002',
      name: 'Pragmatic Play',
      slug: 'pragmatic-play',
      type: 'slots',
      status: 'active',
      logoUrl: '/logos/pragmatic-play.svg',
      website: 'https://www.pragmaticplay.com',
      description: 'Multi-product content provider offering slots, live casino, bingo and virtual sports.',
      integrationType: 'api',
      apiVersion: 'v2.8',
      baseUrl: 'https://api.pragmaticplay.com',
      callbackUrl: 'https://tols-casino.com/callbacks/pragmatic-play',
      secretKey: 'sk_***...pp',
      apiKey: 'ak_***...pp',
      allowedIps: ['104.21.56.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'BRL', 'INR'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'hi', 'id'],
      maxConcurrentSessions: 8000,
      defaultRtp: 96.5,
      isActive: true,
      isCertified: true,
      certifiedAt: '2023-03-22T00:00:00.000Z',
      lastHealthCheck: ts(5),
      totalGames: 580,
      activeGames: 562,
      activePlayers: 8920,
      monthlyRevenue: 2800000,
      errorRate: 0.5,
      avgLatencyMs: 62,
      uptime: 99.95,
      joinedAt: '2022-06-18T00:00:00.000Z',
      createdAt: '2022-06-18T00:00:00.000Z',
    },
    {
      id: 'prov-003',
      name: 'NetEnt',
      slug: 'netent',
      type: 'slots',
      status: 'active',
      logoUrl: '/logos/netent.svg',
      website: 'https://www.netent.com',
      description: 'Legendary slots provider known for premium graphics and innovative game mechanics.',
      integrationType: 'hybrid',
      apiVersion: 'v4.1',
      baseUrl: 'https://api.netent.com',
      callbackUrl: 'https://tols-casino.com/callbacks/netent',
      secretKey: 'sk_***...nt',
      apiKey: 'ak_***...nt',
      allowedIps: ['91.189.44.0/24', '91.189.45.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK', 'NOK', 'CAD'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'sv', 'no', 'fi'],
      maxConcurrentSessions: 6000,
      defaultRtp: 96.8,
      isActive: true,
      isCertified: true,
      certifiedAt: '2022-11-05T00:00:00.000Z',
      lastHealthCheck: ts(8),
      totalGames: 420,
      activeGames: 405,
      activePlayers: 6340,
      monthlyRevenue: 2100000,
      errorRate: 1.2,
      avgLatencyMs: 78,
      uptime: 99.92,
      joinedAt: '2022-01-20T00:00:00.000Z',
      createdAt: '2022-01-20T00:00:00.000Z',
    },
    {
      id: 'prov-004',
      name: "Play'n GO",
      slug: 'playn-go',
      type: 'slots',
      status: 'active',
      logoUrl: '/logos/playn-go.svg',
      website: 'https://www.playngo.com',
      description: 'Mobile-first slots developer with a portfolio of highly volatile, feature-rich games.',
      integrationType: 'api',
      apiVersion: 'v2.5',
      baseUrl: 'https://api.playngo.com',
      callbackUrl: 'https://tols-casino.com/callbacks/playn-go',
      secretKey: 'sk_***...pgo',
      apiKey: 'ak_***...pgo',
      allowedIps: ['172.67.182.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'NZD'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'it'],
      maxConcurrentSessions: 4500,
      defaultRtp: 96.2,
      isActive: true,
      isCertified: true,
      certifiedAt: '2023-05-10T00:00:00.000Z',
      lastHealthCheck: ts(3),
      totalGames: 350,
      activeGames: 338,
      activePlayers: 5670,
      monthlyRevenue: 1900000,
      errorRate: 0.4,
      avgLatencyMs: 55,
      uptime: 99.96,
      joinedAt: '2022-08-02T00:00:00.000Z',
      createdAt: '2022-08-02T00:00:00.000Z',
    },
    {
      id: 'prov-005',
      name: 'Microgaming',
      slug: 'microgaming',
      type: 'slots',
      status: 'active',
      logoUrl: '/logos/microgaming.svg',
      website: 'https://www.microgaming.com',
      description: 'Pioneer of online gaming with the largest progressive jackpot network in the industry.',
      integrationType: 'iframe',
      apiVersion: 'v1.9',
      baseUrl: 'https://api.microgaming.com',
      callbackUrl: 'https://tols-casino.com/callbacks/microgaming',
      secretKey: 'sk_***...mg',
      apiKey: 'ak_***...mg',
      allowedIps: ['195.12.48.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'ZAR', 'NOK'],
      supportedLocales: ['en', 'de', 'fr', 'es', 'pt', 'no', 'af'],
      maxConcurrentSessions: 7000,
      defaultRtp: 96.0,
      isActive: true,
      isCertified: true,
      certifiedAt: '2022-07-28T00:00:00.000Z',
      lastHealthCheck: ts(12),
      totalGames: 650,
      activeGames: 610,
      activePlayers: 4230,
      monthlyRevenue: 1500000,
      errorRate: 0.8,
      avgLatencyMs: 92,
      uptime: 99.88,
      joinedAt: '2021-11-15T00:00:00.000Z',
      createdAt: '2021-11-15T00:00:00.000Z',
    },
    {
      id: 'prov-006',
      name: 'BetConstruct',
      slug: 'betconstruct',
      type: 'sports',
      status: 'suspended',
      logoUrl: '/logos/betconstruct.svg',
      website: 'https://www.betconstruct.com',
      description: 'Sports betting and virtual sports platform currently under compliance review.',
      integrationType: 'api',
      apiVersion: 'v1.4',
      baseUrl: 'https://api.betconstruct.com',
      callbackUrl: 'https://tols-casino.com/callbacks/betconstruct',
      secretKey: 'sk_***...bc',
      apiKey: 'ak_***...bc',
      allowedIps: ['178.62.64.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'RUB', 'GEL'],
      supportedLocales: ['en', 'ru', 'ka', 'es'],
      maxConcurrentSessions: 3000,
      defaultRtp: 95.0,
      isActive: false,
      isCertified: false,
      certifiedAt: null,
      lastHealthCheck: ts(1440),
      totalGames: 180,
      activeGames: 0,
      activePlayers: 0,
      monthlyRevenue: 800000,
      errorRate: 5.2,
      avgLatencyMs: 250,
      uptime: 97.5,
      joinedAt: '2023-02-05T00:00:00.000Z',
      createdAt: '2023-02-05T00:00:00.000Z',
    },
    {
      id: 'prov-007',
      name: 'Ezugi',
      slug: 'ezugi',
      type: 'live_casino',
      status: 'active',
      logoUrl: '/logos/ezugi.svg',
      website: 'https://www.ezugi.com',
      description: 'Live dealer specialist offering boutique tables and localized dealer experiences.',
      integrationType: 'api',
      apiVersion: 'v2.1',
      baseUrl: 'https://api.ezugi.com',
      callbackUrl: 'https://tols-casino.com/callbacks/ezugi',
      secretKey: 'sk_***...ez',
      apiKey: 'ak_***...ez',
      allowedIps: ['52.58.78.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL', 'CLP'],
      supportedLocales: ['en', 'es', 'pt', 'de'],
      maxConcurrentSessions: 2000,
      defaultRtp: 97.1,
      isActive: true,
      isCertified: true,
      certifiedAt: '2023-06-20T00:00:00.000Z',
      lastHealthCheck: ts(4),
      totalGames: 95,
      activeGames: 90,
      activePlayers: 2100,
      monthlyRevenue: 600000,
      errorRate: 0.7,
      avgLatencyMs: 68,
      uptime: 99.93,
      joinedAt: '2023-01-08T00:00:00.000Z',
      createdAt: '2023-01-08T00:00:00.000Z',
    },
    {
      id: 'prov-008',
      name: 'Habanero',
      slug: 'habanero',
      type: 'slots',
      status: 'disconnected',
      logoUrl: '/logos/habanero.svg',
      website: 'https://www.habanerosystems.com',
      description: 'Asian-focused slots and table games provider currently experiencing connectivity issues.',
      integrationType: 'api',
      apiVersion: 'v1.6',
      baseUrl: 'https://api.habanerosystems.com',
      callbackUrl: 'https://tols-casino.com/callbacks/habanero',
      secretKey: 'sk_***...hb',
      apiKey: 'ak_***...hb',
      allowedIps: ['103.28.54.0/24'],
      supportedCurrencies: ['USD', 'EUR', 'CNY', 'THB', 'VND', 'IDR'],
      supportedLocales: ['en', 'zh', 'th', 'vi', 'id', 'ko', 'ja'],
      maxConcurrentSessions: 3500,
      defaultRtp: 96.4,
      isActive: false,
      isCertified: false,
      certifiedAt: null,
      lastHealthCheck: ts(4320),
      totalGames: 280,
      activeGames: 0,
      activePlayers: 0,
      monthlyRevenue: 0,
      errorRate: 0.0,
      avgLatencyMs: 0,
      uptime: 0.0,
      joinedAt: '2023-04-12T00:00:00.000Z',
      createdAt: '2023-04-12T00:00:00.000Z',
    },
  ];

  // ─── Callbacks ────────────────────────────────────────────────────────────────
  const callbacks = [
    { id: 'cb-001', providerId: 'prov-001', name: 'Evolution Session Start', eventType: 'game.session_start', url: 'https://tols-casino.com/callbacks/evolution/game-session', method: 'POST', authType: 'hmac', secretKey: 'sk_***...evo1', ipWhitelist: ['185.26.156.10', '185.26.157.10'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(3), lastSuccessAt: ts(3), totalReceived: 284750, totalSuccess: 284720, totalFailed: 30, avgProcessingMs: 12 },
    { id: 'cb-002', providerId: 'prov-001', name: 'Evolution Bet Placed', eventType: 'game.bet', url: 'https://tols-casino.com/callbacks/evolution/bet', method: 'POST', authType: 'hmac', secretKey: 'sk_***...evo2', ipWhitelist: ['185.26.156.10', '185.26.157.10'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(1), lastSuccessAt: ts(1), totalReceived: 1452800, totalSuccess: 1452700, totalFailed: 100, avgProcessingMs: 8 },
    { id: 'cb-003', providerId: 'prov-001', name: 'Evolution Win Recorded', eventType: 'game.win', url: 'https://tols-casino.com/callbacks/evolution/win', method: 'POST', authType: 'hmac', secretKey: 'sk_***...evo3', ipWhitelist: ['185.26.156.10', '185.26.157.10'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(2), lastSuccessAt: ts(2), totalReceived: 1423600, totalSuccess: 1423550, totalFailed: 50, avgProcessingMs: 9 },
    { id: 'cb-004', providerId: 'prov-002', name: 'Pragmatic Play Session', eventType: 'game.session_start', url: 'https://tols-casino.com/callbacks/pragmatic-play/game-session', method: 'POST', authType: 'bearer', secretKey: 'sk_***...pp1', ipWhitelist: ['104.21.56.12'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(6), lastSuccessAt: ts(6), totalReceived: 198400, totalSuccess: 198380, totalFailed: 20, avgProcessingMs: 15 },
    { id: 'cb-005', providerId: 'prov-002', name: 'Pragmatic Play Bet', eventType: 'game.bet', url: 'https://tols-casino.com/callbacks/pragmatic-play/bet', method: 'POST', authType: 'bearer', secretKey: 'sk_***...pp2', ipWhitelist: ['104.21.56.12'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(2), lastSuccessAt: ts(2), totalReceived: 876200, totalSuccess: 876150, totalFailed: 50, avgProcessingMs: 10 },
    { id: 'cb-006', providerId: 'prov-002', name: 'Pragmatic Play Wallet Credit', eventType: 'wallet.credit', url: 'https://tols-casino.com/callbacks/pragmatic-play/wallet-credit', method: 'POST', authType: 'bearer', secretKey: 'sk_***...pp3', ipWhitelist: ['104.21.56.12'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 200, backoffMultiplier: 2 }, timeoutMs: 2000, lastReceivedAt: ts(1), lastSuccessAt: ts(1), totalReceived: 870100, totalSuccess: 870080, totalFailed: 20, avgProcessingMs: 6 },
    { id: 'cb-007', providerId: 'prov-003', name: 'NetEnt Session End', eventType: 'game.session_end', url: 'https://tols-casino.com/callbacks/netent/game-session', method: 'POST', authType: 'oauth2', secretKey: 'sk_***...nt1', ipWhitelist: ['91.189.44.20', '91.189.45.20'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(15), lastSuccessAt: ts(15), totalReceived: 142600, totalSuccess: 142550, totalFailed: 50, avgProcessingMs: 18 },
    { id: 'cb-008', providerId: 'prov-003', name: 'NetEnt Wallet Debit', eventType: 'wallet.debit', url: 'https://tols-casino.com/callbacks/netent/wallet-debit', method: 'POST', authType: 'oauth2', secretKey: 'sk_***...nt2', ipWhitelist: ['91.189.44.20', '91.189.45.20'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 2000, lastReceivedAt: ts(4), lastSuccessAt: ts(4), totalReceived: 610500, totalSuccess: 610420, totalFailed: 80, avgProcessingMs: 11 },
    { id: 'cb-009', providerId: 'prov-004', name: "Play'n GO Session Start", eventType: 'game.session_start', url: 'https://tols-casino.com/callbacks/playn-go/game-session', method: 'POST', authType: 'bearer', secretKey: 'sk_***...pgo1', ipWhitelist: ['172.67.182.15'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(7), lastSuccessAt: ts(7), totalReceived: 126800, totalSuccess: 126770, totalFailed: 30, avgProcessingMs: 14 },
    { id: 'cb-010', providerId: 'prov-004', name: "Play'n GO Jackpot", eventType: 'game.jackpot', url: 'https://tols-casino.com/callbacks/playn-go/jackpot', method: 'POST', authType: 'bearer', secretKey: 'sk_***...pgo2', ipWhitelist: ['172.67.182.15'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 200, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(180), lastSuccessAt: ts(180), totalReceived: 42, totalSuccess: 42, totalFailed: 0, avgProcessingMs: 22 },
    { id: 'cb-011', providerId: 'prov-005', name: 'Microgaming Bet Limit Change', eventType: 'player.bet_limit_change', url: 'https://tols-casino.com/callbacks/microgaming/bet-limit', method: 'PUT', authType: 'basic', secretKey: 'sk_***...mg1', ipWhitelist: ['195.12.48.30'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(30), lastSuccessAt: ts(30), totalReceived: 8420, totalSuccess: 8410, totalFailed: 10, avgProcessingMs: 25 },
    { id: 'cb-012', providerId: 'prov-005', name: 'Microgaming Wallet Credit', eventType: 'wallet.credit', url: 'https://tols-casino.com/callbacks/microgaming/wallet-credit', method: 'POST', authType: 'basic', secretKey: 'sk_***...mg2', ipWhitelist: ['195.12.48.30'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(5), lastSuccessAt: ts(5), totalReceived: 398600, totalSuccess: 398500, totalFailed: 100, avgProcessingMs: 14 },
    { id: 'cb-013', providerId: 'prov-007', name: 'Ezugi Session Start', eventType: 'game.session_start', url: 'https://tols-casino.com/callbacks/ezugi/game-session', method: 'POST', authType: 'hmac', secretKey: 'sk_***...ez1', ipWhitelist: ['52.58.78.22'], isActive: true, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(10), lastSuccessAt: ts(10), totalReceived: 47800, totalSuccess: 47780, totalFailed: 20, avgProcessingMs: 16 },
    { id: 'cb-014', providerId: 'prov-007', name: 'Ezugi Win', eventType: 'game.win', url: 'https://tols-casino.com/callbacks/ezugi/win', method: 'POST', authType: 'hmac', secretKey: 'sk_***...ez2', ipWhitelist: ['52.58.78.22'], isActive: true, retryPolicy: { maxRetries: 5, backoffMs: 500, backoffMultiplier: 2 }, timeoutMs: 3000, lastReceivedAt: ts(3), lastSuccessAt: ts(3), totalReceived: 235400, totalSuccess: 235380, totalFailed: 20, avgProcessingMs: 10 },
    { id: 'cb-015', providerId: 'prov-006', name: 'BetConstruct Session', eventType: 'game.session_start', url: 'https://tols-casino.com/callbacks/betconstruct/game-session', method: 'POST', authType: 'bearer', secretKey: 'sk_***...bc1', ipWhitelist: ['178.62.64.18'], isActive: false, retryPolicy: { maxRetries: 3, backoffMs: 1000, backoffMultiplier: 2 }, timeoutMs: 5000, lastReceivedAt: ts(10080), lastSuccessAt: ts(10080), totalReceived: 12400, totalSuccess: 12380, totalFailed: 20, avgProcessingMs: 45 },
  ];

  // ─── Games ────────────────────────────────────────────────────────────────────
  const games = [
    { id: 'game-001', providerId: 'prov-005', externalId: 'mg-mega-moolah', name: 'Mega Moolah', slug: 'mega-moolah', type: 'jackpot', category: 'progressive', subCategory: 'african_safari', coverUrl: null, demoUrl: null, rtp: 88.12, volatility: 'high', hitFrequency: 12.5, maxWin: 22500, maxBet: 6.25, minBet: 0.25, defaultBet: 1.0, lines: 25, features: ['progressive_jackpot', 'free_spins', 'wild', 'scatter'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD'], supportedLocales: ['en', 'de', 'fr'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2006-11-01T00:00:00.000Z', totalBets: 58420000, totalWins: 51240000, totalSessions: 1280000, avgSessionMin: 18, popularityScore: 98 },
    { id: 'game-002', providerId: 'prov-001', externalId: 'evo-lightning-roulette', name: 'Lightning Roulette', slug: 'lightning-roulette', type: 'live_table', category: 'roulette', subCategory: 'lightning', coverUrl: null, demoUrl: null, rtp: 97.3, volatility: 'high', hitFrequency: 33.3, maxWin: 500, maxBet: 5000, minBet: 1, defaultBet: 10, lines: 0, features: ['multiplier', 'lightning_numbers', 'live_dealer'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY'], supportedLocales: ['en', 'de', 'ja'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2018-06-01T00:00:00.000Z', totalBets: 124500000, totalWins: 121200000, totalSessions: 2450000, avgSessionMin: 25, popularityScore: 99 },
    { id: 'game-003', providerId: 'prov-004', externalId: 'pgo-book-of-dead', name: 'Book of Dead', slug: 'book-of-dead', type: 'slot', category: 'video_slot', subCategory: 'egyptian', coverUrl: null, demoUrl: null, rtp: 96.21, volatility: 'high', hitFrequency: 22.3, maxWin: 5000, maxBet: 100, minBet: 0.10, defaultBet: 1.0, lines: 10, features: ['free_spins', 'expanding_symbols', 'wild', 'scatter'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD'], supportedLocales: ['en', 'de', 'fr', 'es'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2016-03-01T00:00:00.000Z', totalBets: 89700000, totalWins: 82400000, totalSessions: 3200000, avgSessionMin: 14, popularityScore: 97 },
    { id: 'game-004', providerId: 'prov-002', externalId: 'pp-gates-of-olympus', name: 'Gates of Olympus', slug: 'gates-of-olympus', type: 'slot', category: 'video_slot', subCategory: 'mythology', coverUrl: null, demoUrl: null, rtp: 96.5, volatility: 'high', hitFrequency: 18.4, maxWin: 5000, maxBet: 100, minBet: 0.20, defaultBet: 1.0, lines: 0, features: ['tumble', 'multiplier', 'free_spins', 'ante_bet'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2021-02-01T00:00:00.000Z', totalBets: 105300000, totalWins: 98600000, totalSessions: 2800000, avgSessionMin: 16, popularityScore: 96 },
    { id: 'game-005', providerId: 'prov-003', externalId: 'nt-starburst', name: 'Starburst', slug: 'starburst', type: 'slot', category: 'video_slot', subCategory: 'space', coverUrl: null, demoUrl: null, rtp: 96.09, volatility: 'low', hitFrequency: 22.7, maxWin: 500, maxBet: 100, minBet: 0.10, defaultBet: 1.0, lines: 10, features: ['expanding_wild', 're_spin', 'both_ways'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK'], supportedLocales: ['en', 'de', 'sv'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2012-06-01T00:00:00.000Z', totalBets: 215800000, totalWins: 206000000, totalSessions: 5400000, avgSessionMin: 10, popularityScore: 95 },
    { id: 'game-006', providerId: 'prov-002', externalId: 'pp-sweet-bonanza', name: 'Sweet Bonanza', slug: 'sweet-bonanza', type: 'slot', category: 'video_slot', subCategory: 'candy', coverUrl: null, demoUrl: null, rtp: 96.48, volatility: 'high', hitFrequency: 18.2, maxWin: 21175, maxBet: 100, minBet: 0.20, defaultBet: 1.0, lines: 0, features: ['tumble', 'free_spins', 'multiplier', 'buy_feature', 'ante_bet'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt', 'es'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2019-06-01T00:00:00.000Z', totalBets: 72400000, totalWins: 67800000, totalSessions: 1900000, avgSessionMin: 15, popularityScore: 93 },
    { id: 'game-007', providerId: 'prov-001', externalId: 'evo-crazy-time', name: 'Crazy Time', slug: 'crazy-time', type: 'live_table', category: 'game_show', subCategory: 'wheel', coverUrl: null, demoUrl: null, rtp: 96.28, volatility: 'high', hitFrequency: 33.3, maxWin: 25000, maxBet: 5000, minBet: 0.10, defaultBet: 5, lines: 0, features: ['multiplier', 'bonus_round', 'live_dealer', 'game_show'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'BRL'], supportedLocales: ['en', 'de', 'ja', 'pt'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: true, isNew: false, launchDate: '2020-06-01T00:00:00.000Z', totalBets: 98000000, totalWins: 95200000, totalSessions: 1800000, avgSessionMin: 30, popularityScore: 99 },
    { id: 'game-008', providerId: 'prov-003', externalId: 'nt-gonzos-quest', name: "Gonzo's Quest", slug: 'gonzos-quest', type: 'slot', category: 'video_slot', subCategory: 'adventure', coverUrl: null, demoUrl: null, rtp: 95.97, volatility: 'medium', hitFrequency: 21.6, maxWin: 2500, maxBet: 50, minBet: 0.20, defaultBet: 1.0, lines: 20, features: ['tumble', 'free_spins', 'multiplier', 'avalanche'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'SEK'], supportedLocales: ['en', 'de', 'sv', 'no'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2011-02-01T00:00:00.000Z', totalBets: 68400000, totalWins: 65100000, totalSessions: 2100000, avgSessionMin: 12, popularityScore: 90 },
    { id: 'game-009', providerId: 'prov-002', externalId: 'pp-big-bass-bonanza', name: 'Big Bass Bonanza', slug: 'big-bass-bonanza', type: 'slot', category: 'video_slot', subCategory: 'fishing', coverUrl: null, demoUrl: null, rtp: 96.71, volatility: 'high', hitFrequency: 16.7, maxWin: 2100, maxBet: 50, minBet: 0.10, defaultBet: 1.0, lines: 10, features: ['free_spins', 'collect', 'wild'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2020-12-01T00:00:00.000Z', totalBets: 45200000, totalWins: 42300000, totalSessions: 1500000, avgSessionMin: 11, popularityScore: 88 },
    { id: 'game-010', providerId: 'prov-003', externalId: 'nt-dead-or-alive-2', name: 'Dead or Alive 2', slug: 'dead-or-alive-2', type: 'slot', category: 'video_slot', subCategory: 'wild_west', coverUrl: null, demoUrl: null, rtp: 96.82, volatility: 'high', hitFrequency: 14.2, maxWin: 111111, maxBet: 9, minBet: 0.09, defaultBet: 0.90, lines: 9, features: ['free_spins', 'sticky_wild', 'scatter'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'NOK'], supportedLocales: ['en', 'de', 'no'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2019-04-01T00:00:00.000Z', totalBets: 32100000, totalWins: 29600000, totalSessions: 980000, avgSessionMin: 13, popularityScore: 86 },
    { id: 'game-011', providerId: 'prov-002', externalId: 'pp-wolf-gold', name: 'Wolf Gold', slug: 'wolf-gold', type: 'slot', category: 'video_slot', subCategory: 'nature', coverUrl: null, demoUrl: null, rtp: 96.01, volatility: 'medium', hitFrequency: 24.6, maxWin: 810, maxBet: 50, minBet: 0.25, defaultBet: 1.0, lines: 25, features: ['free_spins', 'money_symbol', 'jackpot', 'wild'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt', 'es'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2018-04-01T00:00:00.000Z', totalBets: 38400000, totalWins: 35400000, totalSessions: 1200000, avgSessionMin: 11, popularityScore: 84 },
    { id: 'game-012', providerId: 'prov-001', externalId: 'evo-immersive-roulette', name: 'Immersive Roulette', slug: 'immersive-roulette', type: 'live_table', category: 'roulette', subCategory: 'immersive', coverUrl: null, demoUrl: null, rtp: 97.3, volatility: 'medium', hitFrequency: 33.3, maxWin: 36, maxBet: 10000, minBet: 1, defaultBet: 25, lines: 0, features: ['live_dealer', 'slow_motion', 'multiple_camera'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY'], supportedLocales: ['en', 'de', 'ja'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2015-01-01T00:00:00.000Z', totalBets: 62500000, totalWins: 60800000, totalSessions: 1100000, avgSessionMin: 22, popularityScore: 87 },
    { id: 'game-013', providerId: 'prov-003', externalId: 'nt-divine-fortune', name: 'Divine Fortune', slug: 'divine-fortune', type: 'jackpot', category: 'progressive', subCategory: 'mythology', coverUrl: null, demoUrl: null, rtp: 96.59, volatility: 'high', hitFrequency: 17.8, maxWin: 600, maxBet: 100, minBet: 0.20, defaultBet: 1.0, lines: 20, features: ['progressive_jackpot', 'free_spins', 'wild', 'falling_wilds'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD'], supportedLocales: ['en', 'de', 'fr'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2017-01-01T00:00:00.000Z', totalBets: 28400000, totalWins: 26200000, totalSessions: 890000, avgSessionMin: 14, popularityScore: 82 },
    { id: 'game-014', providerId: 'prov-004', externalId: 'pgo-reactoonz', name: 'Reactoonz', slug: 'reactoonz', type: 'slot', category: 'video_slot', subCategory: 'sci_fi', coverUrl: null, demoUrl: null, rtp: 96.51, volatility: 'high', hitFrequency: 21.4, maxWin: 4570, maxBet: 100, minBet: 0.20, defaultBet: 1.0, lines: 0, features: ['cluster_pays', 'cascading', 'gargantoon', 'quantum_leap'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD'], supportedLocales: ['en', 'de', 'fr'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2017-10-01T00:00:00.000Z', totalBets: 31200000, totalWins: 29600000, totalSessions: 940000, avgSessionMin: 15, popularityScore: 85 },
    { id: 'game-015', providerId: 'prov-001', externalId: 'evo-blackjack-party', name: 'Blackjack Party', slug: 'blackjack-party', type: 'live_table', category: 'blackjack', subCategory: 'party', coverUrl: null, demoUrl: null, rtp: 99.28, volatility: 'low', hitFrequency: 42.3, maxWin: 1.5, maxBet: 1000, minBet: 5, defaultBet: 25, lines: 0, features: ['live_dealer', 'bet_behind', 'side_bets', 'pre_decision'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY'], supportedLocales: ['en', 'de', 'ja'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2017-06-01T00:00:00.000Z', totalBets: 48200000, totalWins: 47100000, totalSessions: 780000, avgSessionMin: 35, popularityScore: 83 },
    { id: 'game-016', providerId: 'prov-002', externalId: 'pp-money-train-3', name: 'Money Train 3', slug: 'money-train-3', type: 'slot', category: 'video_slot', subCategory: 'western', coverUrl: null, demoUrl: null, rtp: 96.1, volatility: 'high', hitFrequency: 12.4, maxWin: 100000, maxBet: 6, minBet: 0.20, defaultBet: 1.0, lines: 0, features: ['free_spins', 'persistent_symbol', 'buy_feature', 'collect'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2021-11-01T00:00:00.000Z', totalBets: 21800000, totalWins: 19700000, totalSessions: 620000, avgSessionMin: 17, popularityScore: 80 },
    { id: 'game-017', providerId: 'prov-004', externalId: 'pgo-fire-joker', name: 'Fire Joker', slug: 'fire-joker', type: 'slot', category: 'classic_slot', subCategory: 'fruit', coverUrl: null, demoUrl: null, rtp: 96.15, volatility: 'medium', hitFrequency: 34.2, maxWin: 180, maxBet: 50, minBet: 0.05, defaultBet: 1.0, lines: 5, features: ['re_spin', 'multiplier_wheel', 'wild'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD'], supportedLocales: ['en', 'de', 'fr'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2016-06-01T00:00:00.000Z', totalBets: 18900000, totalWins: 17600000, totalSessions: 710000, avgSessionMin: 8, popularityScore: 75 },
    { id: 'game-018', providerId: 'prov-001', externalId: 'evo-baccarat-squeeze', name: 'Baccarat Squeeze', slug: 'baccarat-squeeze', type: 'live_table', category: 'baccarat', subCategory: 'squeeze', coverUrl: null, demoUrl: null, rtp: 98.94, volatility: 'low', hitFrequency: 44.6, maxWin: 9, maxBet: 5000, minBet: 1, defaultBet: 50, lines: 0, features: ['live_dealer', 'squeeze', 'side_bets', 'road_maps'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'BRL'], supportedLocales: ['en', 'de', 'ja', 'pt'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: false, launchDate: '2018-04-01T00:00:00.000Z', totalBets: 34600000, totalWins: 33800000, totalSessions: 520000, avgSessionMin: 28, popularityScore: 79 },
    { id: 'game-019', providerId: 'prov-008', externalId: 'hb-fortune-tiger', name: 'Fortune Tiger', slug: 'fortune-tiger', type: 'slot', category: 'video_slot', subCategory: 'asian', coverUrl: null, demoUrl: null, rtp: 96.81, volatility: 'medium', hitFrequency: 28.4, maxWin: 2500, maxBet: 90, minBet: 0.18, defaultBet: 1.8, lines: 5, features: ['free_spins', 'respin', 'multiplier'], supportedCurrencies: ['CNY', 'THB', 'VND', 'IDR', 'USD'], supportedLocales: ['zh', 'th', 'vi', 'id', 'en'], isMobile: true, isDesktop: true, isLandscape: true, isActive: false, isFeatured: false, isNew: false, launchDate: '2022-03-01T00:00:00.000Z', totalBets: 12400000, totalWins: 11800000, totalSessions: 430000, avgSessionMin: 9, popularityScore: 72 },
    { id: 'game-020', providerId: 'prov-002', externalId: 'pp-plinko', name: 'Plinko', slug: 'plinko', type: 'instant_win', category: 'instant_win', subCategory: 'arcade', coverUrl: null, demoUrl: null, rtp: 97.0, volatility: 'high', hitFrequency: 30.0, maxWin: 420, maxBet: 100, minBet: 0.10, defaultBet: 1.0, lines: 0, features: ['instant_result', 'customizable_rows', 'customizable_risk'], supportedCurrencies: ['USD', 'EUR', 'GBP', 'BRL'], supportedLocales: ['en', 'de', 'pt', 'es'], isMobile: true, isDesktop: true, isLandscape: true, isActive: true, isFeatured: false, isNew: true, launchDate: '2024-01-15T00:00:00.000Z', totalBets: 8400000, totalWins: 7820000, totalSessions: 340000, avgSessionMin: 5, popularityScore: 70 },
  ];

  // ─── Credentials ──────────────────────────────────────────────────────────────
  const credentials = [
    { id: 'cred-001', providerId: 'prov-001', environment: 'production', apiKey: 'ak_***...evo_prod', apiSecret: '***', bearerToken: 'bt_***...evo_prod', certPath: '/certs/evolution/prod.pem', additional: { webSocketUrl: 'wss://ws.evolution.com/v3', operatorId: 'tols_ops_001' }, isActive: true, lastUsedAt: ts(1), expiresAt: '2026-12-31T23:59:59.000Z' },
    { id: 'cred-002', providerId: 'prov-001', environment: 'staging', apiKey: 'ak_***...evo_stg', apiSecret: '***', bearerToken: 'bt_***...evo_stg', certPath: '/certs/evolution/staging.pem', additional: { webSocketUrl: 'wss://ws-stg.evolution.com/v3', operatorId: 'tols_ops_001_stg' }, isActive: true, lastUsedAt: ts(60), expiresAt: '2026-06-30T23:59:59.000Z' },
    { id: 'cred-003', providerId: 'prov-002', environment: 'production', apiKey: 'ak_***...pp_prod', apiSecret: '***', bearerToken: 'bt_***...pp_prod', certPath: null, additional: { operatorId: 'tols_pp_ops', platform: 'pragmatic_play_casino' }, isActive: true, lastUsedAt: ts(2), expiresAt: '2026-09-15T23:59:59.000Z' },
    { id: 'cred-004', providerId: 'prov-003', environment: 'production', apiKey: 'ak_***...nt_prod', apiSecret: '***', bearerToken: 'bt_***...nt_prod', certPath: '/certs/netent/prod.pem', additional: { casinoId: 'tols_casino_001', serverId: 'srv_nt_01' }, isActive: true, lastUsedAt: ts(5), expiresAt: '2025-11-20T23:59:59.000Z' },
    { id: 'cred-005', providerId: 'prov-004', environment: 'production', apiKey: 'ak_***...pgo_prod', apiSecret: '***', bearerToken: 'bt_***...pgo_prod', certPath: null, additional: { channelId: 'tols_pgo_ch', language: 'en' }, isActive: true, lastUsedAt: ts(3), expiresAt: '2026-03-01T23:59:59.000Z' },
    { id: 'cred-006', providerId: 'prov-005', environment: 'production', apiKey: 'ak_***...mg_prod', apiSecret: '***', bearerToken: null, certPath: '/certs/microgaming/prod.pem', additional: { casinoBrand: 'TOLS_CASINO', skinId: 'mg_skin_001' }, isActive: true, lastUsedAt: ts(10), expiresAt: '2025-08-30T23:59:59.000Z' },
    { id: 'cred-007', providerId: 'prov-006', environment: 'production', apiKey: 'ak_***...bc_prod', apiSecret: '***', bearerToken: 'bt_***...bc_prod', certPath: null, additional: { partnerId: 'tols_bc_partner', domain: 'tols-casino.com' }, isActive: false, lastUsedAt: ts(10080), expiresAt: '2025-05-01T23:59:59.000Z' },
    { id: 'cred-008', providerId: 'prov-007', environment: 'production', apiKey: 'ak_***...ez_prod', apiSecret: '***', bearerToken: 'bt_***...ez_prod', certPath: null, additional: { operatorCode: 'TOLS_EZ', streamQuality: 'hd' }, isActive: true, lastUsedAt: ts(4), expiresAt: '2026-07-15T23:59:59.000Z' },
    { id: 'cred-009', providerId: 'prov-008', environment: 'production', apiKey: 'ak_***...hb_prod', apiSecret: '***', bearerToken: 'bt_***...hb_prod', certPath: null, additional: { brandId: 'tols_hb_brand', region: 'asia' }, isActive: false, lastUsedAt: ts(4320), expiresAt: '2025-10-01T23:59:59.000Z' },
    { id: 'cred-010', providerId: 'prov-002', environment: 'sandbox', apiKey: 'ak_***...pp_sbx', apiSecret: '***', bearerToken: 'bt_***...pp_sbx', certPath: null, additional: { operatorId: 'tols_pp_ops_sbx', platform: 'pragmatic_play_casino_sandbox' }, isActive: true, lastUsedAt: ts(120), expiresAt: '2026-09-15T23:59:59.000Z' },
  ];

  // ─── Health Logs ──────────────────────────────────────────────────────────────
  const healthLogs = [
    // Evolution Gaming
    { id: 'hl-001', providerId: 'prov-001', metric: 'error_rate', value: 0.3, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 14280 }, checkedAt: ts(2) },
    { id: 'hl-002', providerId: 'prov-001', metric: 'latency', value: 45, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 32, p95: 68, p99: 124 }, checkedAt: ts(2) },
    { id: 'hl-003', providerId: 'prov-001', metric: 'uptime', value: 99.97, unit: '%', threshold: 99.5, isAlert: false, details: { since: '2025-02-01T00:00:00.000Z', downtimeMinutes: 13 }, checkedAt: ts(2) },
    // Pragmatic Play
    { id: 'hl-004', providerId: 'prov-002', metric: 'error_rate', value: 0.5, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 18420 }, checkedAt: ts(5) },
    { id: 'hl-005', providerId: 'prov-002', metric: 'latency', value: 62, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 48, p95: 112, p99: 198 }, checkedAt: ts(5) },
    { id: 'hl-006', providerId: 'prov-002', metric: 'api_connectivity', value: 1, unit: 'status', threshold: 1, isAlert: false, details: { endpoint: '/game/launch', statusCode: 200 }, checkedAt: ts(5) },
    // NetEnt
    { id: 'hl-007', providerId: 'prov-003', metric: 'error_rate', value: 1.2, unit: '%', threshold: 1.0, isAlert: true, details: { window: '5m', sampleSize: 9840, spikeAt: ts(18) }, checkedAt: ts(8) },
    { id: 'hl-008', providerId: 'prov-003', metric: 'latency', value: 78, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 55, p95: 142, p99: 248 }, checkedAt: ts(8) },
    { id: 'hl-009', providerId: 'prov-003', metric: 'callback_success', value: 99.92, unit: '%', threshold: 99.5, isAlert: false, details: { totalCallbacks: 8420, failed: 7 }, checkedAt: ts(8) },
    // Play'n GO
    { id: 'hl-010', providerId: 'prov-004', metric: 'error_rate', value: 0.4, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 7520 }, checkedAt: ts(3) },
    { id: 'hl-011', providerId: 'prov-004', metric: 'latency', value: 55, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 38, p95: 98, p99: 176 }, checkedAt: ts(3) },
    { id: 'hl-012', providerId: 'prov-004', metric: 'uptime', value: 99.96, unit: '%', threshold: 99.5, isAlert: false, details: { since: '2025-02-01T00:00:00.000Z', downtimeMinutes: 17 }, checkedAt: ts(3) },
    // Microgaming
    { id: 'hl-013', providerId: 'prov-005', metric: 'error_rate', value: 0.8, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 5280 }, checkedAt: ts(12) },
    { id: 'hl-014', providerId: 'prov-005', metric: 'latency', value: 92, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 72, p95: 164, p99: 312 }, checkedAt: ts(12) },
    { id: 'hl-015', providerId: 'prov-005', metric: 'uptime', value: 99.88, unit: '%', threshold: 99.5, isAlert: false, details: { since: '2025-02-01T00:00:00.000Z', downtimeMinutes: 52 }, checkedAt: ts(12) },
    // BetConstruct
    { id: 'hl-016', providerId: 'prov-006', metric: 'error_rate', value: 5.2, unit: '%', threshold: 1.0, isAlert: true, details: { window: '5m', sampleSize: 240, lastHealthyAt: ts(14400) }, checkedAt: ts(1440) },
    { id: 'hl-017', providerId: 'prov-006', metric: 'api_connectivity', value: 0, unit: 'status', threshold: 1, isAlert: true, details: { endpoint: '/sports/events', statusCode: 503, lastOkAt: ts(14400) }, checkedAt: ts(1440) },
    { id: 'hl-018', providerId: 'prov-006', metric: 'latency', value: 250, unit: 'ms', threshold: 200, isAlert: true, details: { p50: 220, p95: 480, p99: 980 }, checkedAt: ts(1440) },
    // Ezugi
    { id: 'hl-019', providerId: 'prov-007', metric: 'error_rate', value: 0.7, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 3120 }, checkedAt: ts(4) },
    { id: 'hl-020', providerId: 'prov-007', metric: 'latency', value: 68, unit: 'ms', threshold: 200, isAlert: false, details: { p50: 48, p95: 124, p99: 210 }, checkedAt: ts(4) },
    { id: 'hl-021', providerId: 'prov-007', metric: 'uptime', value: 99.93, unit: '%', threshold: 99.5, isAlert: false, details: { since: '2025-02-01T00:00:00.000Z', downtimeMinutes: 30 }, checkedAt: ts(4) },
    // Habanero
    { id: 'hl-022', providerId: 'prov-008', metric: 'api_connectivity', value: 0, unit: 'status', threshold: 1, isAlert: true, details: { endpoint: '/game/list', statusCode: null, error: 'ECONNREFUSED', lastOkAt: ts(4320) }, checkedAt: ts(4320) },
    { id: 'hl-023', providerId: 'prov-008', metric: 'error_rate', value: 0.0, unit: '%', threshold: 1.0, isAlert: false, details: { window: '5m', sampleSize: 0, note: 'no_traffic' }, checkedAt: ts(4320) },
    { id: 'hl-024', providerId: 'prov-008', metric: 'uptime', value: 0.0, unit: '%', threshold: 99.5, isAlert: true, details: { since: '2025-02-01T00:00:00.000Z', downtimeMinutes: 43200, note: 'fully_disconnected' }, checkedAt: ts(4320) },
  ];

  // ─── Stats ────────────────────────────────────────────────────────────────────
  const stats = {
    totalProviders: providers.length,
    activeProviders: providers.filter((p) => p.status === 'active').length,
    totalGames: providers.reduce((sum, p) => sum + p.totalGames, 0),
    activeGames: providers.reduce((sum, p) => sum + p.activeGames, 0),
    totalCallbacks: callbacks.length,
    totalActivePlayers: providers.reduce((sum, p) => sum + p.activePlayers, 0),
    totalMonthlyRevenue: providers.reduce((sum, p) => sum + p.monthlyRevenue, 0),
    avgUptime: Number((providers.filter((p) => p.status === 'active').reduce((sum, p) => sum + p.uptime, 0) / providers.filter((p) => p.status === 'active').length).toFixed(2)),
    avgErrorRate: Number((providers.filter((p) => p.status === 'active').reduce((sum, p) => sum + p.errorRate, 0) / providers.filter((p) => p.status === 'active').length).toFixed(2)),
    certifiedProviders: providers.filter((p) => p.isCertified).length,
    pendingProviders: providers.filter((p) => p.status === 'pending').length,
  };

  return NextResponse.json({
    providers,
    callbacks,
    games,
    credentials,
    healthLogs,
    stats,
  });
}
