import { NextResponse } from 'next/server'

const now = new Date()
const ts = (minsAgo: number) => new Date(now.getTime() - minsAgo * 60000).toISOString()

const notifications = [
  // FINANCIAL (7)
  {
    id: 'n-001',
    type: 'success',
    category: 'financial',
    priority: 'normal',
    title: 'Deposit of $5,000 Confirmed',
    message: 'A deposit of $5,000.00 USD from player BigWinner_X has been confirmed via bank transfer. Net amount: $4,975.00',
    read: false,
    actionUrl: '/financial?tab=deposits&id=dep-004',
    createdAt: ts(3),
  },
  {
    id: 'n-002',
    type: 'warning',
    category: 'financial',
    priority: 'high',
    title: 'Withdrawal Pending Approval',
    message: 'A withdrawal of $15,000.00 USD from player BigWinner_X requires manual approval. This exceeds the auto-approve threshold of $10,000.',
    read: false,
    actionUrl: '/payments?tab=withdrawals&id=wd-004',
    createdAt: ts(8),
  },
  {
    id: 'n-003',
    type: 'error',
    category: 'financial',
    priority: 'high',
    title: 'Variance Alert: Marketing spend +25%',
    message: 'Marketing expenditure is 25.3% above budget this period. Threshold is ±15%. Immediate review recommended.',
    read: true,
    actionUrl: '/financial?tab=variance',
    createdAt: ts(15),
  },
  {
    id: 'n-004',
    type: 'info',
    category: 'financial',
    priority: 'normal',
    title: 'Escrow Settlement Completed',
    message: 'Escrow settlement #S-2025-142 completed successfully. $847,500 distributed across 6 waterfall tiers.',
    read: true,
    actionUrl: '/financial?tab=escrow',
    createdAt: ts(45),
  },
  {
    id: 'n-005',
    type: 'success',
    category: 'financial',
    priority: 'low',
    title: 'Revenue Target Met',
    message: 'Weekly revenue target of $2.1M has been achieved. Current week total: $2,187,450. Performance: +4.2% above target.',
    read: true,
    actionUrl: '/dashboard',
    createdAt: ts(120),
  },
  {
    id: 'n-006',
    type: 'warning',
    category: 'financial',
    priority: 'normal',
    title: 'Large Deposit Flagged',
    message: 'Deposit of $25,000 from player HighRoller_X flagged for AML review. Transaction exceeds $10K reporting threshold.',
    read: true,
    actionUrl: '/financial?tab=deposits',
    createdAt: ts(60),
  },
  {
    id: 'n-007',
    type: 'info',
    category: 'financial',
    priority: 'low',
    title: 'Waterfall Distribution Scheduled',
    message: 'Next waterfall distribution scheduled for 2025-03-16 00:00 UTC. Estimated pool: $1,245,000.',
    read: true,
    actionUrl: '/financial?tab=waterfall',
    createdAt: ts(180),
  },

  // PLAYER (6)
  {
    id: 'n-008',
    type: 'info',
    category: 'player',
    priority: 'low',
    title: 'New Player Registration: AlexK_99',
    message: 'New player AlexK_99 registered from Canada. Initial deposit: $100 USD. Source: organic_search.',
    read: true,
    actionUrl: '/players?id=p-120',
    createdAt: ts(5),
  },
  {
    id: 'n-009',
    type: 'warning',
    category: 'player',
    priority: 'high',
    title: 'High Value Player Login: HighRoller_X',
    message: 'VIP Level 5 player HighRoller_X logged in from new device/location: Toronto, CA. Lifetime value: $142,500.',
    read: false,
    actionUrl: '/players?id=p-104',
    createdAt: ts(10),
  },
  {
    id: 'n-010',
    type: 'info',
    category: 'player',
    priority: 'normal',
    title: 'Player Level Up: CryptoKing99',
    message: 'Player CryptoKing99 reached VIP Level 3. Qualifying wager total: $15,200. Bonus awarded: 500 USDT.',
    read: true,
    actionUrl: '/players?id=p-102',
    createdAt: ts(35),
  },
  {
    id: 'n-011',
    type: 'success',
    category: 'player',
    priority: 'normal',
    title: 'Player Reactivated: SleepBear_42',
    message: 'Dormant player SleepBear_42 (inactive 45 days) returned and deposited $200. Reactivation bonus applied.',
    read: true,
    actionUrl: '/players?id=p-118',
    createdAt: ts(90),
  },
  {
    id: 'n-012',
    type: 'warning',
    category: 'player',
    priority: 'high',
    title: 'Suspicious Login Attempt',
    message: 'Multiple failed login attempts for player LuckyDraw_77 from IP 185.220.101.42 (known VPN exit node). Account temporarily locked.',
    read: true,
    actionUrl: '/players?id=p-119',
    createdAt: ts(20),
  },
  {
    id: 'n-013',
    type: 'info',
    category: 'player',
    priority: 'normal',
    title: 'Player Segment Updated',
    message: 'Segment "High Value - Active" updated: 12 players added, 3 removed. Total segment size: 247.',
    read: true,
    actionUrl: '/segments',
    createdAt: ts(150),
  },

  // SYSTEM (4)
  {
    id: 'n-014',
    type: 'warning',
    category: 'system',
    priority: 'high',
    title: 'API Token Expiring in 7 Days',
    message: 'API token "Staging Environment" (tols_b7d4n2p5) expires on 2025-03-20. Generate a new token to avoid service interruption.',
    read: false,
    actionUrl: '/api-hub?tab=tokens',
    createdAt: ts(30),
  },
  {
    id: 'n-015',
    type: 'info',
    category: 'system',
    priority: 'normal',
    title: 'System Maintenance Scheduled',
    message: 'Planned maintenance window: 2025-03-17 02:00-04:00 UTC. Expected downtime: 15 minutes. All services affected.',
    read: true,
    actionUrl: '/api-hub',
    createdAt: ts(240),
  },
  {
    id: 'n-016',
    type: 'success',
    category: 'system',
    priority: 'normal',
    title: 'Backup Completed Successfully',
    message: 'Daily database backup completed. Size: 2.4 GB. Duration: 8m 32s. Stored: s3://tols-backups/2025-03-15/',
    read: true,
    actionUrl: '/api-hub',
    createdAt: ts(300),
  },
  {
    id: 'n-017',
    type: 'error',
    category: 'system',
    priority: 'urgent',
    title: 'Server Node Degraded: US-West',
    message: 'Server node US-West (Oregon) status changed to degraded. CPU: 89%, Memory: 92%. Auto-scaling triggered. Investigate immediately.',
    read: false,
    actionUrl: '/live-map',
    createdAt: ts(1),
  },

  // WEBHOOK (3)
  {
    id: 'n-018',
    type: 'error',
    category: 'webhook',
    priority: 'high',
    title: 'Webhook Delivery Failed: 3 retries',
    message: 'Webhook "Variance Alerts" delivery failed after 3 retries to https://partner.com/webhooks/variance. Last status: 503 Service Unavailable.',
    read: true,
    actionUrl: '/api-hub?tab=webhooks',
    createdAt: ts(25),
  },
  {
    id: 'n-019',
    type: 'warning',
    category: 'webhook',
    priority: 'urgent',
    title: 'Webhook Latency Spike',
    message: 'Webhook "Player Activity" experiencing elevated latency. Average response time: 2.8s (normal: 150ms). 5 timeouts in last hour.',
    read: true,
    actionUrl: '/api-hub?tab=webhooks',
    createdAt: ts(55),
  },
  {
    id: 'n-020',
    type: 'success',
    category: 'webhook',
    priority: 'high',
    title: 'Webhook Endpoint Verified',
    message: 'Webhook endpoint https://partner.com/webhooks/compliance verified successfully. Challenge response received in 89ms.',
    read: true,
    actionUrl: '/api-hub?tab=webhooks',
    createdAt: ts(180),
  },

  // INTEGRATION (3)
  {
    id: 'n-021',
    type: 'critical',
    category: 'integration',
    priority: 'urgent',
    title: 'Integration Sync Error: Custom Platform X',
    message: 'Custom Platform X sync failed with 3 consecutive errors: AUTH_FAILED, TIMEOUT, RATE_LIMIT. Sync paused. Manual intervention required.',
    read: false,
    actionUrl: '/api-hub?tab=integrations',
    createdAt: ts(12),
  },
  {
    id: 'n-022',
    type: 'info',
    category: 'integration',
    priority: 'normal',
    title: 'Integration Sync Progress: PokerStars',
    message: 'PokerStars sync in progress: 8,940 / 12,000 records (74.5%). Estimated completion: 12 minutes.',
    read: true,
    actionUrl: '/api-hub?tab=integrations',
    createdAt: ts(6),
  },
  {
    id: 'n-023',
    type: 'success',
    category: 'integration',
    priority: 'normal',
    title: 'Integration Sync Complete: BetMGM',
    message: 'BetMGM Casino sync completed. 15,230 records processed. Duration: 4m 18s. No errors detected.',
    read: true,
    actionUrl: '/api-hub?tab=integrations',
    createdAt: ts(95),
  },

  // COMPLIANCE (2)
  {
    id: 'n-024',
    type: 'critical',
    category: 'compliance',
    priority: 'high',
    title: 'KYC Flag: Player requires verification',
    message: 'Player Diamond_Hand flagged for KYC review. Reason: Government ID document expired 7 days ago. Deposit and withdrawal capabilities restricted.',
    read: false,
    actionUrl: '/players?id=p-107',
    createdAt: ts(18),
  },
  {
    id: 'n-025',
    type: 'critical',
    category: 'compliance',
    priority: 'urgent',
    title: 'Self-Exclusion Request: Player123',
    message: 'Player Player123 submitted a self-exclusion request for 6 months. All active sessions terminated. Account locked effective immediately. Marketing outreach disabled.',
    read: false,
    actionUrl: '/players?id=p-123',
    createdAt: ts(7),
  },
]

const preferences = [
  { id: 'pref-001', category: 'financial', inApp: true, email: true, sms: false, webhook: true, push: false },
  { id: 'pref-002', category: 'player', inApp: true, email: true, sms: false, webhook: false, push: false },
  { id: 'pref-003', category: 'system', inApp: true, email: true, sms: false, webhook: false, push: true },
  { id: 'pref-004', category: 'webhook', inApp: true, email: false, sms: false, webhook: false, push: false },
  { id: 'pref-005', category: 'integration', inApp: true, email: true, sms: false, webhook: false, push: true },
  { id: 'pref-006', category: 'compliance', inApp: true, email: true, sms: true, webhook: true, push: true },
]

const templates = [
  {
    id: 'tmpl-001',
    key: 'deposit_confirmed',
    name: 'Deposit Confirmed',
    subject: 'Deposit of {{amount}} {{currency}} Confirmed',
    body: 'A deposit of {{amount}} {{currency}} from player {{playerName}} ({{playerId}}) has been confirmed via {{method}}. Net amount: {{netAmount}} {{currency}}. Transaction ID: {{txId}}.',
    category: 'financial',
    variables: ['amount', 'currency', 'playerName', 'playerId', 'method', 'netAmount', 'txId'],
  },
  {
    id: 'tmpl-002',
    key: 'withdrawal_pending',
    name: 'Withdrawal Pending Approval',
    subject: 'Withdrawal of {{amount}} {{currency}} Requires Approval',
    body: 'A withdrawal of {{amount}} {{currency}} from player {{playerName}} ({{playerId}}) is pending approval. Method: {{method}}. Requested at: {{requestedAt}}.',
    category: 'financial',
    variables: ['amount', 'currency', 'playerName', 'playerId', 'method', 'requestedAt'],
  },
  {
    id: 'tmpl-003',
    key: 'variance_alert',
    name: 'Variance Alert',
    subject: 'Variance Alert: {{category}} {{direction}}{{percentage}}%',
    body: 'Variance threshold exceeded for {{category}}. Current variance: {{direction}}{{percentage}}% (threshold: ±{{threshold}}%). Period: {{period}}. Review recommended.',
    category: 'financial',
    variables: ['category', 'direction', 'percentage', 'threshold', 'period'],
  },
  {
    id: 'tmpl-004',
    key: 'player_registration',
    name: 'Player Registration',
    subject: 'New Player Registration: {{playerName}}',
    body: 'New player {{playerName}} ({{playerId}}) registered from {{country}}. Initial deposit: {{initialDeposit}} {{currency}}. Source: {{source}}.',
    category: 'player',
    variables: ['playerName', 'playerId', 'country', 'initialDeposit', 'currency', 'source'],
  },
  {
    id: 'tmpl-005',
    key: 'high_value_login',
    name: 'High Value Player Login',
    subject: 'High Value Player Login: {{playerName}}',
    body: 'VIP Level {{vipLevel}} player {{playerName}} ({{playerId}}) logged in from {{location}}. Lifetime value: {{lifetimeValue}} {{currency}}. {{deviceInfo}}.',
    category: 'player',
    variables: ['playerName', 'playerId', 'vipLevel', 'location', 'lifetimeValue', 'currency', 'deviceInfo'],
  },
  {
    id: 'tmpl-006',
    key: 'api_token_expiring',
    name: 'API Token Expiring',
    subject: 'API Token "{{tokenName}}" Expiring in {{daysRemaining}} Days',
    body: 'API token "{{tokenName}}" ({{tokenPreview}}) expires on {{expiresAt}}. Generate a new token at the API Hub to avoid service interruption. Affected scopes: {{scopes}}.',
    category: 'system',
    variables: ['tokenName', 'tokenPreview', 'daysRemaining', 'expiresAt', 'scopes'],
  },
  {
    id: 'tmpl-007',
    key: 'webhook_failed',
    name: 'Webhook Delivery Failed',
    subject: 'Webhook "{{webhookName}}" Delivery Failed',
    body: 'Webhook "{{webhookName}}" delivery to {{url}} failed after {{retryCount}} retries. Last HTTP status: {{statusCode}}. Event: {{event}}. Error: {{errorMessage}}.',
    category: 'webhook',
    variables: ['webhookName', 'url', 'retryCount', 'statusCode', 'event', 'errorMessage'],
  },
  {
    id: 'tmpl-008',
    key: 'kyc_flag',
    name: 'KYC Verification Flag',
    subject: 'KYC Flag: Player {{playerName}} Requires Verification',
    body: 'Player {{playerName}} ({{playerId}}) flagged for KYC review. Reason: {{flagReason}}. Account capabilities restricted until verification is complete. Flagged at: {{flaggedAt}}.',
    category: 'compliance',
    variables: ['playerName', 'playerId', 'flagReason', 'flaggedAt'],
  },
]

const channels = [
  { id: 'ch-001', type: 'email', name: 'Email', address: 'ops@tols-casino.com', verified: true, lastUsedAt: ts(3) },
  { id: 'ch-002', type: 'sms', name: 'SMS', address: '+1-555-0142', verified: true, lastUsedAt: ts(60) },
  { id: 'ch-003', type: 'webhook', name: 'Webhook', address: 'https://internal.tols/notify', verified: true, lastUsedAt: ts(5) },
  { id: 'ch-004', type: 'slack', name: 'Slack', address: '#tols-alerts', verified: true, lastUsedAt: ts(12) },
  { id: 'ch-005', type: 'discord', name: 'Discord', address: 'TOLS Operations', verified: false, lastUsedAt: '' },
]

const stats = {
  total: 25,
  unread: 8,
  byCategory: {
    financial: 7,
    player: 6,
    system: 4,
    webhook: 3,
    integration: 3,
    compliance: 2,
  },
  byPriority: {
    low: 3,
    normal: 10,
    high: 8,
    urgent: 4,
  },
  byType: {
    info: 7,
    warning: 6,
    success: 6,
    error: 3,
    critical: 3,
  },
}

export async function GET() {
  return NextResponse.json({
    notifications,
    preferences,
    templates,
    channels,
    stats,
  })
}
